Add support and testing for new Django and Python versions
twidi/django-decorator-include pull request #83
Opened 2020-12-10 16:31 UTC by jdufresne

Django 3.1 was released August 4, 2020.

Python 3.9 was released October 5th, 2020.

2020-12-10 16:45 UTC, twidi commented on README.rst
>  2.2             3.5, 3.6, 3.7, 3.8
+3.9

2020-12-10 16:46 UTC, twidi commented on tox.ini
>      py{35,36,37,38}-django22
+`,39`

2020-12-10 16:48 UTC, twidi commented on README.rst
>  2.2             3.5, 3.6, 3.7, 3.8      3.0
+`, 3.9`

2020-12-10 16:49 UTC, twidi requested changes
You missed to add python 3.9 for django 2.2 at some places

2020-12-10 21:16 UTC, jdufresne commented
Thanks for catching that. Fixed in the latest revision.

2020-12-12 14:00 UTC, twidi approved these changes

2020-12-12 15:16 UTC, merged