Remove support for end-of-life Python and Django versions
twidi/django-decorator-include pull request #84
Opened 2020-12-10 16:37 UTC by jdufresne

For a list of supported Python versions, see:
https://devguide.python.org/#status-of-python-branches

For a list of end-of-life Python versions, see:
https://devguide.python.org/devcycle/#end-of-life-branches

For a list of supported Django versions, see:
https://www.djangoproject.com/download/#supported-versions

By removing testing for end-of-life versions, we reduce testing time and
resources.

2020-12-10 16:50 UTC, twidi commented on setup.cfg
>  install_requires = Django>=2.0
2.2

2020-12-10 16:52 UTC, twidi requested changes
Just one remark

2020-12-10 21:21 UTC, jdufresne commented
Good catch. Fixed in the latest revision.

2020-12-11 09:06 UTC, twidi commented
I guess we have to migrate from travis to another CI tool....  :-/

2020-12-11 12:16 UTC, twidi commented
> I guess we have to migrate from travis to another CI tool.... :-/

I'll try to work on it this week-end, with circle-ci (or github actions but I never used it).

2020-12-11 15:24 UTC, jdufresne commented
Agreed. While Travis is **super slow** it eventually finished. Thoughts on merging these PRs in the meantime?

2020-12-12 13:58 UTC, twidi approved these changes

2020-12-12 15:10 UTC, merged